### ISSUE TITLE
四号機の振動について

### ISSUE THREAD

**Issue by shimoe** [CIR-KIT/fourth_robot_driver#1]
@RyodoTanaka 
四号機のモータ？まわりについてです。
駆動輪が宙に浮いた状態で駆動輪を手で回すと一定の範囲で振動するのですが何が原因かわかりますか？
4号機が自立した状態で手で押して走らせると振動は気にならないので問題ないのかもしれませんが、解決したいです。
よろしくお願いします。

P.S.
4号機のデコデコユニットはいつ頃まで必要ですか？

**Comment by RyodoTanaka** [comment]
@shimoe 
遅くなってごめんなさい。
4号機のモータは振動しているのではないと思われます。
モータがタイヤに接続されている際、タイヤを空回転させると、当然のことながら、モータも回転します。
すると、モータの回転により起電力が発生します。この起電力は、モータに接続されているモータドライバに流れることになります。
ゆえに、タイヤの回転数を上げると起電力は大きくなり、それが原因でモータドライバの回路が故障してしまうことがあります。
このような故障を防ぐために、いくつかのモータドライバでは予め設定しておいたしきい値以上のモータからの起電力を観測すると、回路を保護するために、モータブレーキをかけるような設計がなされています。これは、４号機で使用しているモータドライバでも同じです。
故に、感じているのは振動ではなく、モータドライバによるブレーキだと思います。また、それは仕様なので、防ぐ方法はありません。（この仕様のおかげで適当な設計をしていても回路がぶっ壊れないですんでいるとも言えます）

DC/DCユニットについてですが、本日(2015/5/13)に持ってゆきます。
